---
openapi: 3.0.1
info:
  title: API v1.0
  version: v1.0
components:
  schemas:
    errors_object:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
      required:
      - errors
    money_send_transaction_full:
      type: object
      properties:
        id:
          type: integer
          format: int64
        amount:
          type: number
          format: double
        status:
          type: string
          enum:
          - declined
          - pending
          - succeeded
        sender_id:
          type: integer
          format: int64
        receiver_id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
      - id
      - amount
      - status
      - sender_id
      - receiver_id
      - created_at
      - updated_at
    money_send_transaction_partial:
      type: object
      properties:
        amount:
          type: number
          format: double
        sender_id:
          type: integer
          format: int64
        receiver_id:
          type: integer
          format: int64
      required:
      - amount
      - sender_id
      - receiver_id
paths:
  "/accounts/{id}/money_send_transactions":
    get:
      summary: Get all Account.find(id)'s money send transactions
      tags:
      - Account Money Sendings
      parameters:
      - name: id
        in: path
        schema:
          type: integer
          format: int64
        required: true
      responses:
        '201':
          description: Account.find(id)'s money send transactions fetched
          content:
            application/json:
              example:
                data:
                - id: 1
                  amount: '1.23'
                  status: succeeded
                  created_at: '2020-01-01T00:00:00.000Z'
                  updated_at: '2020-01-01T00:00:00.000Z'
                  sender_id: 1
                  receiver_id: 2
                - id: 2
                  amount: '45.67'
                  status: declined
                  created_at: '2020-01-01T00:00:00.000Z'
                  updated_at: '2020-01-01T00:00:00.000Z'
                  sender_id: 1
                  receiver_id: 2
        '422':
          description: Invalid request
          content:
            application/json:
              example:
                errors:
                - Request is missing required parameters. Please check OpenAPI spec
                  and see if it mathces. Contact support if this error presist despite
                  matching OpenAPI spec.
  "/accounts/{id}/money_receive_transactions":
    get:
      summary: Get all Account.find(id)'s money receive transactions
      tags:
      - Account Money Receivings
      parameters:
      - name: id
        in: path
        schema:
          type: integer
          format: int64
        required: true
      responses:
        '201':
          description: Account.find(id)'s money receive transactions fetched
          content:
            application/json:
              example:
                data:
                - id: 1
                  amount: '1.23'
                  status: succeeded
                  created_at: '2020-01-01T00:00:00.000Z'
                  updated_at: '2020-01-01T00:00:00.000Z'
                  sender_id: 1
                  receiver_id: 2
                - id: 2
                  amount: '45.67'
                  status: declined
                  created_at: '2020-01-01T00:00:00.000Z'
                  updated_at: '2020-01-01T00:00:00.000Z'
                  sender_id: 1
                  receiver_id: 2
        '422':
          description: Invalid request
          content:
            application/json:
              example:
                errors:
                - Request is missing required parameters. Please check OpenAPI spec
                  and see if it mathces. Contact support if this error presist despite
                  matching OpenAPI spec.
  "/money_send_transaction":
    post:
      summary: Creates a transaction
      tags:
      - Money Send Transactions
      parameters: []
      responses:
        '201':
          description: Transaction created
          content:
            application/json:
              example:
                id: 1
                amount: '3.01'
                status: succeeded
                created_at: '2020-01-01T00:00:00.000Z'
                updated_at: '2020-01-01T00:00:00.000Z'
                sender_id: 1
                receiver_id: 2
        '422':
          description: Invalid request
          content:
            application/json:
              example:
                errors:
                - Request is missing required parameters. Please check OpenAPI spec
                  and see if it mathces. Contact support if this error presist despite
                  matching OpenAPI spec.
        '403':
          description: 'Forbidden: Account pending or unverified'
          content:
            application/json:
              example:
                errors:
                - Unverified and pending accounts cannot send or receive transacctions.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/money_send_transaction_partial"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
